srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 1867036.0 ON nid0638 CANCELLED AT 2023-08-09T01:04:14 ***
slurmstepd: error: *** JOB 1867036 ON nid0638 CANCELLED AT 2023-08-09T01:04:14 ***
Process ForkPoolWorker-550178:
Process ForkPoolWorker-550175:
Process ForkPoolWorker-550173:
Process ForkPoolWorker-550174:
Process ForkPoolWorker-550177:
Process ForkPoolWorker-550176:
Process ForkPoolWorker-550179:
Process ForkPoolWorker-550182:
Process ForkPoolWorker-550184:
Process ForkPoolWorker-550180:
Process ForkPoolWorker-550185:
Process ForkPoolWorker-550181:
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)

During handling of the above exception, another exception occurred:

  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)

During handling of the above exception, another exception occurred:

  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-550183:
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.5/Lib/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
