srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 1876620.0 ON nid0638 CANCELLED AT 2023-08-19T17:41:18 ***
slurmstepd: error: *** JOB 1876620 ON nid0638 CANCELLED AT 2023-08-19T17:41:18 ***
Process ForkPoolWorker-6917:
Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
